In [11]:
import numpy as np

a = np.arange(15)
a = a.reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [12]:
import numpy as np

print('Create an array with values in the range from 0 to 14 using "a = np.arange(15)".')
a = np.arange(15)
print('Arrange comes from the numpy library, which we imported as np, '
    'so the header "np." is required.')
print(a)
print()

print('Reshape the array using "a = a.reshape(3,5)".')
a = a.reshape(3,5)
print(a)
print()

print('Python indexes from 0, so to access the value located in the third row, second column, we can do "a[3-1,2-1]".')
print(a[3-1,2-1])
print()

print('However, to access the same value more elegantly, we should just do "a[2,1]".')
print(a[2,1])
print('The output is the same, of course.')
print()

print('What is the shape of this array? Use "a.shape"')
print(a.shape)
print()

print('How many dimensions does this array have? Use "a.ndim".')
print(a.ndim)
print()


Create an array with values in the range from 0 to 14 using "a = np.arange(15)".
Arrange comes from the numpy library, which we imported as np, so the header "np." is required.
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Reshape the array using "a = a.reshape(3,5)".
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Python indexes from 0, so to access the value located in the third row, second column, we can do "a[3-1,2-1]".
11

However, to access the same value more elegantly, we should just do "a[2,1]".
11
The output is the same, of course.

What is the shape of this array? Use "a.shape"
(3, 5)

How many dimensions does this array have? Use "a.ndim".
2



In [13]:
b = np.array([1,2,3,4])
c = np.arange(10)
for i in b:
    #if()
    print(i)
    print(i+c)
    print()

print(b)
print(c)

1
[ 1  2  3  4  5  6  7  8  9 10]

2
[ 2  3  4  5  6  7  8  9 10 11]

3
[ 3  4  5  6  7  8  9 10 11 12]

4
[ 4  5  6  7  8  9 10 11 12 13]

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [70]:
print('Creating an array with 9 evenly-spaced numbers inclusively from 0 to 2 ')
d = np.linspace( 0, 2, 9 )
print(d)


Creating an array with 9 evenly-spaced numbers inclusively from 0 to 2 
[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]


In [38]:
import numpy as np
n=5
print('We have ', n, ' particles.')
print()
posn = np.array([0.5,0.7,0.9,1.3,2.2])
print('Positions are:')
print(posn)
print(sum(posn))
print()
print()
momt = np.array([(12,17,13,25,4),(11,16,10,5,41),(2,7,123,5,24)])
print('Momenta are:')
print(momt)
sum(momt, axis=0)

We have  5  particles.

Positions are:
[ 0.5  0.7  0.9  1.3  2.2]
5.6


Momenta are:
[[ 12  17  13  25   4]
 [ 11  16  10   5  41]
 [  2   7 123   5  24]]


array([ 25,  40, 146,  35,  69])

In [71]:
print('The size of momt is',  momt.size,'.')
print('Given that we have', n, 'particles, we must have', momt.size/n, 'points in time.')
print('The dim of momt is', momt.ndim,'.')
print('The shape of momt is',momt.shape,'.')
print('The size of momt is',momt.size,'.')

The size of momt is 15 .
Given that we have 5 particles, we must have 3.0 points in time.
The dim of momt is 2 .
The shape of momt is (3, 5) .
The size of momt is 15 .


In [50]:
print(momt)
np.sum(np.sum(momt, axis=0),axis=0)
sum(sum(momt))
print()
print()
print(momt*momt)
print()
print()
sum(sum(momt*momt))

[[ 12  17  13  25   4]
 [ 11  16  10   5  41]
 [  2   7 123   5  24]]


[[  144   289   169   625    16]
 [  121   256   100    25  1681]
 [    4    49 15129    25   576]]




19209

In [142]:
test = np.array([0.5,0.7,0.9,1.3,2.2])
a = test.shape[0]
semifac = np.zeros((int(scipy.special.comb(a,2)),1))
k=0;
#print(a)
for i in range(0,a):
    print('i=',i)
    for j in range(i,a):
        if i != j:
            semifac[k] = test[i]*test[j]
            k=k+1
            print('j=',j)
print(semifac)

i= 0
j= 1
j= 2
j= 3
j= 4
i= 1
j= 2
j= 3
j= 4
i= 2
j= 3
j= 4
i= 3
j= 4
i= 4
[[ 0.35]
 [ 0.45]
 [ 0.65]
 [ 1.1 ]
 [ 0.63]
 [ 0.91]
 [ 1.54]
 [ 1.17]
 [ 1.98]
 [ 2.86]]


In [112]:
%reset
import numpy as np
import scipy.special

position = np.array([0.5,0.7,0.9,1.3,2.2])
N=5;
sigma=1;
L=1;
eps=0.25;

alphas = (-1, 0, 1)

#We have three values in alpha, so we must calculate potentials three times
distance = np.zeros( (int(scipy.special.comb(N,2)),1) )
u_1 = np.zeros( (int(scipy.special.comb(N,2))) )
u_2 = np.zeros( (int(scipy.special.comb(N,2))) )
u_3 = np.zeros( (int(scipy.special.comb(N,2))) )

print(position)
print(type(position))
print()

print(alphas)
print(type(alphas))
print()

print(type(u_1))
print(u_1)
print()

k=0
for i in range(0,N):
    for j in range(i,N):
        if i != j:
            distance[k] = abs(position[j] - position[i]) - L*alphas[0]
            u_1[k] = 4*eps*((sigma/distance[k][0])**12 - (sigma/distance[k][0])**6)
            k=k+1
            
k=0
for i in range(0,N):
    for j in range(i,N):
        if i != j:
            distance[k] = abs(position[j] - position[i]) - L*alphas[1]
            u_2[k] = 4*eps*((sigma/distance[k][0])**12 - (sigma/distance[k][0])**6)
            k=k+1
            
k=0
for i in range(0,N):
    for j in range(i,N):
        if i != j:
            distance[k] = abs(position[j] - position[i]) - L*alphas[2]
            u_3[k] = 4*eps*((sigma/distance[k][0])**12 - (sigma/distance[k][0])**6)
            k=k+1
            
print(type(u_1))
print('u_1 = ',u_1)
print()



Once deleted, variables cannot be recovered. Proceed (y/[n])? y
[ 0.5  0.7  0.9  1.3  2.2]
<class 'numpy.ndarray'>

(-1, 0, 1)
<class 'tuple'>

<class 'numpy.ndarray'>
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]

<class 'numpy.ndarray'>
u_1 =  [-0.22274132 -0.11517173 -0.02853676 -0.00257451 -0.22274132 -0.05605193
 -0.00407922 -0.11517173 -0.00670949 -0.02080403]



In [42]:
%reset
import numpy as np


e1 = 1,2,30
print(e1)
print(e1[1])
print(type(e1))
print(type(e1[1]))
print()
e2 = 21, 22, 23
print(e2)
print()
print()

e = ((e1, e2))
print(e)
print(type(e))
print(e[1])
print(e[1][1])
print()

et = e1 + e2
print(et)
print(type(et))
print(et[1])

Once deleted, variables cannot be recovered. Proceed (y/[n])? y
(1, 2, 30)
2
<class 'tuple'>
<class 'int'>

(21, 22, 23)


((1, 2, 30), (21, 22, 23))
<class 'tuple'>
(21, 22, 23)
22

(1, 2, 30, 21, 22, 23)
<class 'tuple'>
2


In [109]:
%reset
import numpy as np

u = (0,1,2,3,4,5)
print(u[0:4:2])
print()
b=[0,0,0,0]
b[0:4] = [3,3,3,3]
print(b)
print(type(b))

d = (4,'e')
print(d)
print(type(d))

print(d[0:2])
d=list(d)
print(d)
print(type(d))
d[1] = 'r'
print(d)
d = tuple(d)
print(d)
print(type(d))

Once deleted, variables cannot be recovered. Proceed (y/[n])? y
(0, 2)

[3, 3, 3, 3]
<class 'list'>
(4, 'e')
<class 'tuple'>
(4, 'e')
[4, 'e']
<class 'list'>
[4, 'r']
(4, 'r')
<class 'tuple'>


In [126]:
%reset
import numpy as np
import scipy.special

position = np.array([[0.5,0.7,0.9,1.3,2.2],[3,4,5,6,7],[0,0,0,0,0]])
print(position)
print()
print(position[0,0])


Once deleted, variables cannot be recovered. Proceed (y/[n])? y
[[ 0.5  0.7  0.9  1.3  2.2]
 [ 3.   4.   5.   6.   7. ]
 [ 0.   0.   0.   0.   0. ]]

0.5
